include: package:very_good_analysis/analysis_options.5.0.0.yaml

linter:
  rules:
    always_use_package_imports: false
    cascade_invocations: false
    camel_case_types: false
    no_leading_underscores_for_local_identifiers: false
    prefer_relative_imports: true
    public_member_api_docs: false
    sort_constructors_first: false
    non_constant_identifier_names: false

analyzer:
  plugins:
    - custom_lint
  exclude:
    - '**/*.g.dart'
    - '**/*.gr.dart'
