name: supabase_client_provider
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: 3.19.6

dependencies:
  flutter:
    sdk: flutter
  logging: 1.1.1
  supabase_flutter: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1
