name: sentry_repository
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: 3.12.0

dependencies:
  device_info_plus: ^9.0.1
  flutter:
    sdk: flutter
  logging: 1.1.1
  sentry_flutter: ^7.6.1
  sentry_logging: ^7.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1
