name: flow_test
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  meta: ^1.8.0

dev_dependencies:
  very_good_analysis: ^5.0.0+1
