name: pieces_painter
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: 3.19.6

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
