name: device_info_provider
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: 3.19.0

dependencies:
  device_info_plus: ^9.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1
