// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKoEKKN3nwsI3Ky2Bcua_fAXuzdZCbXuw',
    appId: '1:675316094808:android:0a804cba6a65522097772d',
    messagingSenderId: '675316094808',
    projectId: 'compass-b9364',
    storageBucket: 'compass-b9364.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8l8KuB6LXUxSf5WgONbPBLl1zyHau5E0',
    appId: '1:675316094808:ios:eaf89becbeb9292397772d',
    messagingSenderId: '675316094808',
    projectId: 'compass-b9364',
    storageBucket: 'compass-b9364.firebasestorage.app',
    androidClientId: '675316094808-g599103prclmj6i2qo1e00schcacivfr.apps.googleusercontent.com',
    iosClientId: '675316094808-d24rhbsag5mdgjnp0acpd6djag5h37sf.apps.googleusercontent.com',
    iosBundleId: 'com.gadfly361.gadflyfluttertemplate',
  );
}
