name: amplitude_repository
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: 3.12.0

dependencies:
  amplitude_flutter: ^3.16.0
  auto_route: ^7.2.0
  flutter:
    sdk: flutter
  logging: 1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1
