name: file_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  device_info_plus: ^11.4.0
  file_picker: ^10.1.9
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
