include: package:very_good_analysis/analysis_options.5.0.0.yaml

linter:
  rules:
    avoid_returning_this: false
    avoid_equals_and_hash_code_on_mutable_classes: false
    prefer_constructors_over_static_methods: false
