name: supabase_tests
on:
  push:
    branches:
      - main
    paths:
      - 'supabase/**'
      - '.github/workflows/supabase_tests.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'supabase/**'
      - '.github/workflows/supabase_tests.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.88.0
      - name: Supabase Start
        run: supabase start
      - name: Run Tests
        run: supabase test db