name: app_theme
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: 3.12.0

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1
